<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>KLIDO</title><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700;800;900&display=swap" rel="stylesheet"><script src="https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js"></script><script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.0/dist/chart.umd.min.js"></script><style>
*{box-sizing:border-box}body{margin:0;font-family:Inter;background:#0b1020;color:#e2e8f0;height:100vh;overflow:hidden}
.app{display:flex;flex-direction:column;height:100vh;padding:10px}.topbar{height:74px;background:#131b2e;border:1px solid #1e2a4a;border-radius:14px 14px 0 0;display:flex;align-items:center;justify-content:space-between;padding:0 16px}
.menu{width:240px;background:#0f172a;border-right:1px solid #1e2a4a;padding:12px;display:flex;flex-direction:column;gap:3px;overflow:auto}
.m{padding:11px 12px;border-radius:10px;color:#94a3b8;cursor:pointer;font-size:13.5px;display:flex;gap:10px;transition:0.15s;user-select:none;border:1px solid transparent;background:transparent}
.m:hover{background:#1e293b!important;color:#fff!important}
.m.active{background:#3b82f6!important;color:#fff!important;font-weight:700;border-color:#3b82f6!important}
.api-input{width:100%;padding:9px 11px;border-radius:8px;border:1px solid #2a3a5c;background:#0b1020;color:#fff;margin:5px 0;font-size:13px}
.teamCard{background:#1e293b;border:1px solid #2a3a5c;border-radius:12px;padding:12px;margin:8px 0;display:flex;justify-content:space-between;align-items:center}
.view{position:absolute;inset:0;background:#0f172a;z-index:5;display:none;flex-direction:column;padding:20px;overflow:auto}
.inbox{width:380px;background:#0f172a;border-right:1px solid #1e2a4a;display:flex;flex-direction:column}
.chat{flex:1;background:#0f172a;display:flex;flex-direction:column}.msgs{flex:1;overflow:auto;padding:18px;display:flex;flex-direction:column;gap:10px}
.b{max-width:70%;padding:11px 14px;border-radius:16px;font-size:13px}.b.cli{background:#1e293b;align-self:flex-start}.b.age{background:#bfdbfe;color:#0f172a;align-self:flex-end}
.profile{width:360px;background:#0f172a;border-left:1px solid #1e2a4a;padding:14px;overflow:auto;display:none}.profile.show{display:block}
.kpi{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:12px 0}.kpiCard{background:#1e293b;border:1px solid #2a3a5c;border-radius:12px;padding:14px}
.planCard{background:#131b2e;border:1px solid #1e2a4a;border-radius:14px;padding:18px;text-align:center}.planBtn{background:#3b82f6;border:0;padding:11px;border-radius:10px;color:#fff;font-weight:700;width:100%;cursor:pointer;margin-top:12px}
.wpp-float{position:fixed;bottom:20px;right:20px;width:56px;height:56px;background:#25D366;border-radius:50%;display:flex;align-items:center;justify-content:center;box-shadow:0 4px 12px #0006;z-index:999;cursor:pointer}
.wpp-logo-only{width:72px;height:72px;background:#25D366;border-radius:50%;display:flex;align-items:center;justify-content:center;cursor:pointer;box-shadow:0 2px 8px #0004}
</style></head><body>
<div class="app">
<div class="topbar"><div style="display:flex;align-items:center;gap:14px"><img src="/logo.png" style="width:58px;height:58px;border-radius:12px;background:#fff;padding:4px"><div><div style="display:flex;gap:6px"><span style="font-size:26px;font-weight:900">KLIDO</span><span style="font-size:15px;font-weight:600;color:#cbd5e1">Avanza Consulting</span></div><div style="font-size:10px;color:#93c5fd;font-weight:800">API OFICIAL META</div></div></div><div style="display:flex;gap:12px;align-items:center"><span id="userEmail" style="font-size:12px;color:#94a3b8"></span><button onclick="salir()" style="background:#ef4444;border:0;padding:7px 14px;border-radius:8px;color:#fff;font-weight:700;cursor:pointer">Salir</button></div></div>
<div style="flex:1;display:flex;background:#131b2e;border:1px solid #1e2a4a;border-top:0;border-radius:0 0 14px 14px;overflow:hidden">
<div class="menu" id="sideMenu">
<div style="font-size:10px;color:#64748b;margin:8px;font-weight:700">MENU</div>
<div class="m active" id="mInbox" onclick="showView('inbox')">📥 Inbox</div>
<div class="m" id="mCamp" onclick="showView('camp')">🔔 Campaigns</div>
<div class="m" id="mPlan" onclick="showView('plan')">💳 Planes</div>
<div class="m" id="mCal" onclick="showView('calendar')">📅 Calendario <span id="calCount" style="margin-left:auto;background:#ef4444;color:#fff;padding:2px 6px;border-radius:10px;font-size:10px;display:none">0</span></div>
<div class="m" id="mStats" onclick="showView('stats')">📊 Estadísticas</div>
<div class="m" id="mMetrics" onclick="showView('metrics')">📈 Métricas</div>
<div class="m" id="mTeam" onclick="showView('team')">👥 Equipos</div>
<div class="m" id="mConfig" onclick="showView('config')">⚙️ Configuración</div>
<div style="font-size:10px;color:#64748b;margin:14px 8px 6px">SUPPORT</div>
<div class="m" id="mSupport" onclick="showView('support')">💡 Help Center / Soporte</div>
<div style="margin-top:auto;padding:8px;background:#1e293b;border:1px solid #2a3a5c;border-radius:12px"><div id="planBadge" style="font-size:11px;font-weight:700">Plan básico</div><div style="font-size:10px;color:#64748b">Gestiona tu suscripción</div></div>
</div>

<div id="inboxArea" style="display:flex;flex:1">
<div class="inbox"><div style="padding:12px 14px;display:flex;justify-content:space-between"><b>Inbox</b><span id="countInbox" style="font-size:11px;color:#94a3b8">0 chats</span></div><div style="padding:0 12px"><input id="q" class="api-input" placeholder="Buscar..." oninput="loadChats()"></div><div id="list" style="flex:1;overflow:auto"></div></div>
<div class="chat"><div style="height:60px;border-bottom:1px solid #1e2a4a;display:flex;align-items:center;padding:0 14px;gap:10px"><div id="hAv" style="width:36px;height:36px;border-radius:50%;background:#a5b4fc;color:#000;display:flex;align-items:center;justify-content:center;font-weight:700">SN</div><div><div id="hName" style="font-weight:700;font-size:14px">Selecciona un chat</div><div style="font-size:11px;color:#22c55e">WhatsApp Business API</div></div></div><div class="msgs" id="msgs"><div style="text-align:center;color:#64748b;margin-top:80px">Selecciona conversación</div></div><div style="padding:10px 12px;border-top:1px solid #1e2a4a;display:flex;gap:10px"><input id="txt" class="api-input" style="margin:0;flex:1;border-radius:22px" placeholder="Type a message..." onkeydown="if(event.key==='Enter') sendMsg()"><button style="width:38px;height:38px;border-radius:50%;background:#3b82f6;border:0;color:#fff" onclick="sendMsg()">▶</button></div></div>
<div class="profile show" id="profilePanel"><div style="display:flex;justify-content:space-between"><b>Customer Profile</b><span onclick="profilePanel.classList.remove('show')" style="cursor:pointer">✕</span></div><div style="display:flex;gap:10px;align-items:center;justify-content:center;flex-direction:column;margin-top:10px"><div id="pAv" style="width:56px;height:56px;border-radius:50%;background:#3b82f6;color:#fff;display:flex;align-items:center;justify-content:center;font-weight:700">SN</div><div id="pNameEdit" contenteditable="true" style="font-weight:700">-</div><div id="pPhone" style="font-size:11px;color:#94a3b8"></div></div><select id="pEstado" class="api-input" onchange="saveProfile()"><option value="nuevo">nuevo</option><option value="cliente">cliente</option><option value="interesado">interesado</option></select><input id="pNombre" class="api-input" placeholder="Nombre" onblur="saveProfile()"><input id="pCiudad" class="api-input" placeholder="Ciudad" onblur="saveProfile()"><input id="pProfesion" class="api-input" placeholder="Cargo" onblur="saveProfile()"><input id="pEmpresa" class="api-input" placeholder="Empresa" onblur="saveProfile()"><select id="pOrigen" class="api-input" onchange="saveProfile()"><option value="">Origen</option><option value="campana">Campaña</option><option value="afiliado">Afiliado</option></select><input id="pCamp" class="api-input" placeholder="Campaña" onblur="saveProfile()"><textarea id="pNotes" class="api-input" style="min-height:70px" onblur="saveProfile()"></textarea><div id="pTags"></div><div style="display:flex;gap:6px"><input id="newTag" class="api-input" style="flex:1" placeholder="Tag"><button onclick="addTag()" style="background:#3b82f6;border:0;padding:8px 12px;border-radius:8px;color:#fff">+</button></div><select id="pAgendaEstado" class="api-input"><option value="">--</option><option value="pendiente">Pendiente</option><option value="agendado">Agendado</option></select><input id="pAgendaFecha" type="datetime-local" class="api-input"><input id="pAgendaNota" class="api-input" placeholder="Nota"><button onclick="agendarCliente()" style="width:100%;background:#f59e0b;border:0;padding:9px;border-radius:8px;color:#000;font-weight:800">+ Agendar</button></div>
</div>

<div id="mainFull" style="flex:1;position:relative;display:none">

<div class="view" id="planView" style="background:#0b1020"><h2>Planes KLIDO - Anual</h2><div style="display:grid;grid-template-columns:1fr 1fr 1fr;gap:16px;max-width:900px">
<div class="planCard"><div style="font-weight:700">Básico</div><div style="font-size:28px;font-weight:900;margin:8px 0">$800.000</div><div style="font-size:12px;color:#94a3b8">anual</div><div style="font-size:11px;color:#3b82f6;font-weight:700">+ $80.000 mant. c/3 meses</div><div style="text-align:left;font-size:12px;line-height:22px;margin-top:10px"><div>✅ 1 envio masivo</div><div>✅ 2 usuarios</div><div>✅ 1000 mensajes</div><div>❌ Sin IA</div></div><button class="planBtn" onclick="elegirPlan('basico')">Empezar Básico</button></div>
<div class="planCard"><div style="font-weight:700">Premium ⭐</div><div style="font-size:28px;font-weight:900;margin:8px 0">$1.300.000</div><div style="font-size:12px;color:#94a3b8">anual</div><div style="font-size:11px;color:#3b82f6;font-weight:700">+ $95.000 mant. c/3 meses</div><div style="text-align:left;font-size:12px;line-height:22px;margin-top:10px"><div>✅ 5 envios simultáneos</div><div>✅ 5 usuarios</div><div>✅ IA incluida</div><div>✅ Soporte prioritario</div></div><button class="planBtn" onclick="elegirPlan('premium')">Empezar Premium</button></div>
<div class="planCard"><div style="font-weight:700">Gold</div><div style="font-size:28px;font-weight:900;margin:8px 0">$2.400.000</div><div style="font-size:12px;color:#94a3b8">anual</div><div style="font-size:11px;color:#3b82f6;font-weight:700">+ $130.000 mant. c/3 meses</div><div style="text-align:left;font-size:12px;line-height:22px;margin-top:10px"><div>✅ Envíos ilimitados</div><div>✅ Usuarios ilimitados</div><div>✅ IA + Pánico humano</div><div>✅ Llamada directa</div></div><button class="planBtn" onclick="elegirPlan('gold')">Empezar Gold</button></div>
</div></div>

<div class="view" id="configView" style="background:#0b1020"><div style="display:flex;justify-content:space-between"><h2>⚙️ Configuración - Todo sobre KLIDO</h2><button onclick="showView('inbox')" style="background:#1e293b;border:1px solid #2a3a5c;color:#fff;padding:6px 12px;border-radius:8px">Volver</button></div>
<div style="display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-top:12px">
<div style="background:#131b2e;border:1px solid #1e2a4a;border-radius:14px;padding:16px"><h3 style="color:#3b82f6;margin:0 0 8px">📥 Mensajes</h3><p style="font-size:12px;color:#cbd5e1">API Oficial Meta, fotos, videos, audios reproducibles, documentos. Inbox Todos/No leídos punto rojo desaparece al responder. Customer profile solo bandeja. Tags, notas.</p></div>
<div style="background:#131b2e;border:1px solid #1e2a4a;border-radius:14px;padding:16px"><h3 style="color:#22c55e;margin:0 0 8px">📊 Estadísticas</h3><p style="font-size:12px;color:#cbd5e1">Graficadas Chart.js, mismos datos métricas, chats por trabajador barras, estado dona, seguimiento línea. Total chats, recordatorios, equipo.</p></div>
<div style="background:#131b2e;border:1px solid #1e2a4a;border-radius:14px;padding:16px"><h3 style="color:#f59e0b;margin:0 0 8px">📈 Métricas</h3><p style="font-size:12px;color:#cbd5e1">Resultados por trabajador, número chats, avance %, seguimiento, mensajes enviados, no leídos. Grupal % atendidos.</p></div>
<div style="background:#131b2e;border:1px solid #1e2a4a;border-radius:14px;padding:16px"><h3 style="margin:0 0 8px">🔔 Campaigns</h3><p style="font-size:12px;color:#cbd5e1">Excel cualquier columna cualquier orden regex, 50 cada 4h anti-baneo, pausar/continuar, historial progreso, plantillas APPROVED válidas sin importar variables/fotos/cuerpo. Gmail solo Gold bloqueado en Básico.</p></div>
</div>
<div style="margin-top:16px;background:#131b2e;border:1px solid #3b82f6;border-radius:14px;padding:16px"><h3>💳 Planes y Funciones</h3><div style="display:grid;grid-template-columns:1fr 1fr 1fr;gap:12px;font-size:12px"><div style="background:#0b1020;padding:12px;border-radius:10px"><b>Básico $800k + $80k trim</b><br>• 1 envío<br>• 2 usuarios<br>• 1000 mensajes<br>• Sin IA</div><div style="background:#0b1020;padding:12px;border-radius:10px;border:1px solid #3b82f6"><b>Premium $1.3M + $95k ⭐</b><br>• 5 envíos<br>• 5 usuarios<br>• IA<br>• Soporte prio</div><div style="background:#0b1020;padding:12px;border-radius:10px"><b>Gold $2.4M + $130k</b><br>• Ilimitados<br>• Usuarios ilimit<br>• IA + Pánico<br>• Llamada + Gmail</div></div></div>
<div style="margin-top:16px;background:#131b2e;border:1px solid #ef4444;border-radius:14px;padding:16px"><h3 style="color:#f59e0b;margin:0 0 8px">🔑 Token Meta, WABA ID, Phone - Solo admin ve - Acepta 1 día 60 días permanente</h3><div style="display:grid;grid-template-columns:1fr 1fr 1fr;gap:12px;font-size:11px"><div style="background:#0b1020;padding:10px;border-radius:8px"><b>TOKEN</b><br>Acepta 1 día, 60 días y permanente. Recomendado permanente Nunca Expira. Guarda en base, trabajadores usan cache sin verlo.</div><div style="background:#0b1020;padding:10px;border-radius:8px"><b>WABA ID</b><br>ID cuenta WhatsApp Business no Business ID. Si pones Business ID sale 0 plantillas.</div><div style="background:#0b1020;padding:10px;border-radius:8px"><b>PHONE ID</b><br>ID número no el número. Para enviar y webhook.</div></div><button onclick="openApi()" style="margin-top:12px;background:#3b82f6;border:0;padding:10px 16px;border-radius:8px;color:#fff;font-weight:700">🔑 Configurar API (Admin)</button></div>
</div>

<div class="view" id="supportView" style="background:#0b1020"><div style="display:flex;justify-content:space-between"><h2>💡 Help Center / Soporte KLIDO</h2><button onclick="showView('inbox')" style="background:#1e293b;border:1px solid #2a3a5c;color:#fff;padding:6px 12px;border-radius:8px">Volver</button></div>
<div style="display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-top:12px">
<div style="background:#131b2e;border:1px solid #1e2a4a;border-radius:14px;padding:16px"><h3>📞 Contacto Directo</h3><p style="font-size:12px;color:#cbd5e1">Soporte prioritario KLIDO Avanza Consulting</p>
<div style="margin-top:20px;display:flex;flex-direction:column;align-items:center;gap:12px">
<a href="https://wa.me/573133181851?text=Hola%20soporte%20KLIDO" target="_blank" class="wpp-logo-only" title="Soporte WhatsApp"><svg viewBox="0 0 32 32" width="36" height="36" fill="white"><path d="M16 3C9.373 3 4 8.373 4 15c0 2.251.59 4.36 1.63 6.19L4 29l8.07-1.56A11.94 11.94 0 0016 27c6.627 0 12-5.373 12-12S22.627 3 16 3zm0 2c5.514 0 10 4.486 10 10s-4.486 10-10 10c-1.95 0-3.77-.56-5.31-1.52l-.38-.23-4.8.93.97-4.67-.25-.39A9.94 9.94 0 016 15c0-5.514 4.486-10 10-10zm-3.5 5.5c-.28 0-.72.1-1.1.5-.38.4-1.45 1.42-1.45 3.46s1.48 4.01 1.69 4.29c.21.28 2.91 4.45 7.06 6.24.34.14.61.22.82.28.34.11.65.09.89.06.27-.04.82-.34.94-.66.12-.33.12-.61.08-.67-.04-.06-.14-.09-.29-.15s-.89-.44-1.03-.49c-.14-.05-.24-.08-.34.08-.1.16-.39.49-.48.59-.09.1-.18.11-.33.04-.15-.07-.64-.24-1.22-.76-.45-.4-.76-.9-.85-1.05-.09-.16-.01-.24.07-.32.07-.07.15-.18.23-.27.07-.09.1-.15.15-.25.05-.1.02-.19-.01-.26-.03-.07-.34-.82-.47-1.12-.12-.29-.25-.34-.25h-.29c-.1 0-.26.04-.4.19-.14.15-.53.52-.53 1.27s.54 1.47.62 1.57c.07.1 1.06 1.62 2.57 2.27.36.15.64.24.86.31.36.11.69.1.95.06.29-.04.89-.36 1.01-.72.12-.35.12-.66.08-.72-.04-.06-.14-.1-.29-.16z"/></svg></a>
<span style="font-size:11px;color:#94a3b8">Toca el logo para hablar con soporte - 24/7</span>
</div>
<div style="margin-top:18px;background:#0b1020;padding:12px;border-radius:10px;font-size:12px"><b>Email:</b> soporte@klidoapp.com.co<br><b>Horario:</b> Soporte 24/7</div>
</div>
<div style="background:#131b2e;border:1px solid #1e2a4a;border-radius:14px;padding:16px"><h3>❓ Preguntas Frecuentes</h3><div style="font-size:11px;line-height:18px;color:#cbd5e1"><b>¿Plantillas no cargan?</b> Verifica WABA ID (no Business ID) y token con whatsapp_business_management. Aceptamos 1 día, 60 días y permanente.<br><br><b>¿50 cada 4h?</b> Anti-baneo Meta.<br><br><b>¿Token visible?</b> Solo admin.<br><br><b>¿Eliminar único admin?</b> No deja.<br><br><b>¿Excel cualquier columna?</b> Sí, regex cualquier hoja.</div></div>
</div>
</div>

<div class="view" id="calView"><div style="display:flex;justify-content:space-between;align-items:center"><h2>📅 Calendario - Trabajadores organizados y Citas</h2><button onclick="showView('inbox')" style="background:#1e293b;border:1px solid #2a3a5c;color:#fff;padding:6px 12px;border-radius:8px">Volver</button></div><div id="calList" style="margin-top:12px"></div></div>

<div class="view" id="statsView"><div style="display:flex;justify-content:space-between"><h2>📊 Estadísticas</h2><button onclick="showView('inbox')" style="background:#1e293b;border:1px solid #2a3a5c;color:#fff;padding:6px 12px;border-radius:8px">Volver</button></div><div class="kpi"><div class="kpiCard"><div style="font-size:11px;color:#94a3b8">CHATS</div><div id="sChats" style="font-size:28px;font-weight:800">0</div></div><div class="kpiCard"><div style="font-size:11px;color:#94a3b8">RECORDATORIOS</div><div id="sCals" style="font-size:28px;font-weight:800">0</div></div><div class="kpiCard"><div style="font-size:11px;color:#94a3b8">PENDIENTES</div><div id="sSeg" style="font-size:28px;font-weight:800">0</div></div><div class="kpiCard"><div style="font-size:11px;color:#94a3b8">EQUIPO</div><div id="sTeam" style="font-size:28px;font-weight:800">0</div></div></div><div style="display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-top:12px"><div style="background:#1e293b;border:1px solid #2a3a5c;border-radius:12px;padding:12px"><canvas id="chartTrabajador"></canvas></div><div style="background:#1e293b;border:1px solid #2a3a5c;border-radius:12px;padding:12px"><canvas id="chartEstado"></canvas></div></div></div>
<div class="view" id="metricsView"><div style="display:flex;justify-content:space-between"><h2>📈 Métricas</h2><button onclick="showView('inbox')" style="background:#1e293b;border:1px solid #2a3a5c;color:#fff;padding:6px 12px;border-radius:8px">Volver</button></div><div id="metricsKpi" class="kpi"></div><div id="metricsWorkers"></div><div id="metricsGeneral"></div></div>
<div class="view" id="teamView"><div style="display:flex;justify-content:space-between"><h2>👥 Equipos</h2><button onclick="showView('inbox')" style="background:#1e293b;border:1px solid #2a3a5c;color:#fff;padding:6px 12px;border-radius:8px">Volver</button></div><div style="background:#1e293b;border:1px solid #2a3a5c;border-radius:12px;padding:14px;margin:12px 0;display:flex;gap:8px"><input id="eqEmail" class="api-input" style="flex:1" placeholder="Email"><input id="eqPass" class="api-input" style="flex:1" placeholder="Pass" type="password"><select id="eqRol" class="api-input" style="width:120px"><option value="agente">Agente</option><option value="admin">Admin</option></select><button onclick="addWorker()" style="background:#3b82f6;border:0;padding:9px 16px;border-radius:8px;color:#fff;font-weight:700">+ Añadir</button></div><div id="teamList"></div></div>

<div class="view" id="campView" style="padding:0;display:none"><div style="padding:20px;overflow:auto;height:100%">
<div style="display:flex;justify-content:space-between"><h2>🔔 Campaigns - Plantillas Aprobadas API Oficial</h2><button onclick="showView('inbox')" style="background:#1e293b;border:1px solid #2a3a5c;color:#fff;padding:6px 12px;border-radius:8px">Volver</button></div>
<p style="font-size:12px;color:#94a3b8">Acepta token 1 día, 60 días y permanente - Recomendado permanente pero todos cargan plantillas - Gmail solo Gold bloqueado en Básico</p>
<div style="background:#1e293b;border:1px solid #2a3a5c;border-radius:14px;padding:16px;margin:12px 0">
<div style="display:grid;grid-template-columns:1fr 1fr;gap:12px"><input id="campNombre" class="api-input" placeholder="Nombre campaña"><select id="campTipo" class="api-input" onchange="toggleTipo()"><option value="whatsapp">WhatsApp - Acepta 1d 60d permanente</option><option value="gmail">Gmail Gold - Solo Gold (Básico bloqueado)</option></select></div>
<div id="whatsappBlock"><div style="margin-top:12px"><label style="font-size:11px;color:#22c55e;font-weight:700">✅ Plantillas - Seguimiento variables y header</label><div style="display:flex;gap:8px"><select id="campTemplate" class="api-input" style="flex:1" onchange="onTemplateChange()"><option>Cargando plantillas aprobadas...</option></select><button onclick="loadTemplates()" style="background:#1e293b;border:1px solid #2a3a5c;color:#fff;padding:8px 12px;border-radius:8px">🔄 Recargar</button></div><div id="templateInfo" style="font-size:11px;color:#93c5fd;margin-top:6px;background:#0b1020;padding:8px;border-radius:8px">Cargando...</div></div><div id="varBlock" style="margin-top:10px;background:#0b1020;padding:8px;border-radius:8px"></div></div>
<div id="gmailBlock" style="display:none"><input id="gmailSubject" class="api-input" placeholder="Asunto Gmail Gold"><textarea id="gmailBody" class="api-input" style="min-height:80px" placeholder="Cuerpo Gmail Gold"></textarea><div style="font-size:10px;color:#f59e0b">⛔ Gmail solo Gold - Básico bloqueado</div></div>
<div style="display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:14px"><div style="background:#0b1020;border:1px dashed #3b82f6;border-radius:12px;padding:12px"><b>📊 Excel cualquier columna</b><input type="file" id="excelFile" accept=".xlsx,.xls,.csv" onchange="parseExcel()" style="margin-top:8px"><div id="excelResult" style="font-size:12px;color:#22c55e"></div></div><div style="background:#0b1020;border:1px dashed #f59e0b;border-radius:12px;padding:12px"><b>✍️ Manual</b><textarea id="manualNums" class="api-input" style="min-height:90px" oninput="parseManual()"></textarea><div id="manualResult"></div></div></div>
<div style="margin-top:12px;background:#0f172a;border:1px solid #3b82f6;border-radius:10px;padding:12px;display:flex;justify-content:space-between"><b id="totalNums">0 contactos - 50 cada 4h anti-baneo</b><button onclick="crearCamp()" style="background:#22c55e;border:0;padding:12px 22px;border-radius:10px;color:#000;font-weight:800">🚀 Crear y Enviar</button></div>
</div>
<div style="padding:20px"><h3 style="margin:0 0 10px">📜 Historial de campañas - Pausar / Continuar - Seguimiento</h3><div id="campHistory" style="max-height:400px;overflow:auto"></div></div>
</div></div>

</div>
</div>
</div>

<a href="https://wa.me/573133181851?text=Hola%20soporte%20KLIDO" target="_blank" class="wpp-float" title="Soporte"><svg viewBox="0 0 32 32" width="30" height="30" fill="white"><path d="M16 3C9.373 3 4 8.373 4 15c0 2.251.59 4.36 1.63 6.19L4 29l8.07-1.56A11.94 11.94 0 0016 27c6.627 0 12-5.373 12-12S22.627 3 16 3zm0 2c5.514 0 10 4.486 10 10s-4.486 10-10 10c-1.95 0-3.77-.56-5.31-1.52l-.38-.23-4.8.93.97-4.67-.25-.39A9.94 9.94 0 016 15c0-5.514 4.486-10 10-10zm-3.5 5.5c-.28 0-.72.1-1.1.5-.38.4-1.45 1.42-1.45 3.46s1.48 4.01 1.69 4.29c.21.28 2.91 4.45 7.06 6.24.34.14.61.22.82.28.34.11.65.09.89.06.27-.04.82-.34.94-.66.12-.33.12-.61.08-.67-.04-.06-.14-.09-.29-.15s-.89-.44-1.03-.49c-.14-.05-.24-.08-.34.08-.1.16-.39.49-.48.59-.09.1-.18.11-.33.04-.15-.07-.64-.24-1.22-.76-.45-.4-.76-.9-.85-1.05-.09-.16-.01-.24.07-.32.07-.07.15-.18.23-.27.07-.09.1-.15.15-.25.05-.1.02-.19-.01-.26-.03-.07-.34-.82-.47-1.12-.12-.29-.25-.34-.25h-.29c-.1 0-.26.04-.4.19-.14.15-.53.52-.53 1.27s.54 1.47.62 1.57c.07.1 1.06 1.62 2.57 2.27.36.15.64.24.86.31.36.11.69.1.95.06.29-.04.89-.36 1.01-.72.12-.35.12-.66.08-.72-.04-.06-.14-.1-.29-.16z"/></svg></a>

<div id="apiModal" style="display:none;position:fixed;inset:0;background:#000a;align-items:center;justify-content:center;z-index:99"><div style="background:#131b2e;border:1px solid #1e2a4a;padding:18px;border-radius:14px;width:440px"><h3>🔑 Settings API - Solo admin - Acepta 1 día 60 días permanente</h3><div id="apiCurrent" style="font-size:11px;background:#0b1020;padding:8px;border-radius:8px;margin-bottom:8px;color:#94a3b8"></div><div id="apiAdminOnly"><input id="apiPhone" class="api-input" placeholder="Phone Number ID"><input id="apiWaba" class="api-input" placeholder="WABA ID (no Business ID)"><input id="apiToken" class="api-input" placeholder="Token 1 día / 60 días / permanente - recomendado permanente"></div><div id="apiMsg" style="font-size:12px;color:#22c55e;margin:8px 0"></div><button onclick="saveApi()" style="background:#22c55e;border:0;padding:9px;border-radius:8px;color:#fff;width:100%">Guardar en base - Acepta todos</button><button onclick="apiModal.style.display='none';showView('inbox')" style="background:#1e293b;border:0;padding:9px;border-radius:8px;color:#fff;width:100%;margin-top:6px">Cerrar</button></div></div>

<script>
let S={}, curChat=null, allChats=[], detected=[], templates=[], excelNums=[], manualNums=[], chart1=null, chart2=null;
function init(){const eid=localStorage.getItem('klido_empresa'); const u=localStorage.getItem('klido_user'); if(!eid||!u){location.href='/'; return;} S={eid, user:JSON.parse(u)}; document.getElementById('userEmail').innerText=S.user.email+' ('+S.user.rol+')'; document.getElementById('planBadge').innerText='Plan '+(localStorage.getItem('klido_plan')||'básico'); loadChats(); loadConfigAndTemplates(); setInterval(loadChats,5000);}
function clearMenu(){ document.querySelectorAll('#sideMenu.m').forEach(el=>el.classList.remove('active')); }
function showView(v){
  clearMenu();
  document.querySelectorAll('.view').forEach(e=>e.style.display='none');
  document.getElementById('inboxArea').style.display='none';
  document.getElementById('mainFull').style.display='none';
  const prof=document.getElementById('profilePanel'); if(prof) prof.classList.remove('show');
  const idMap={inbox:'mInbox', camp:'mCamp', plan:'mPlan', calendar:'mCal', stats:'mStats', metrics:'mMetrics', team:'mTeam', config:'mConfig', support:'mSupport'};
  const activeEl=document.getElementById(idMap[v]); if(activeEl) activeEl.classList.add('active');
  if(v==='inbox'){ document.getElementById('inboxArea').style.display='flex'; document.getElementById('profilePanel').classList.add('show'); }
  else{
    document.getElementById('mainFull').style.display='flex';
    const viewId=v+'View'; const viewEl=document.getElementById(viewId); if(viewEl) viewEl.style.display='flex';
    if(v==='camp') document.getElementById('campView').style.display='block';
    if(v==='calendar') loadCalendar();
    if(v==='stats') loadStatsGrafica();
    if(v==='metrics') loadMetricsWorkers();
    if(v==='team') loadTeam();
    if(v==='camp'){ loadCampHistory(); loadTemplates(); }
  }
}
function salir(){localStorage.clear();location.href='/';}
async function loadChats(){const r=await fetch('/api/chats/'+S.eid+'/admin'); allChats=await r.json(); document.getElementById('countInbox').innerText=allChats.length+' chats'; const q=(document.getElementById('q').value||'').toLowerCase(); const list=document.getElementById('list'); list.innerHTML=''; let filtered=allChats.filter(c=>{ if(q &&!((c.nombre||'').toLowerCase().includes(q)||c.id.includes(q))) return false; return true;}); filtered.forEach(c=>{const d=document.createElement('div'); d.style.cssText='display:flex;gap:10px;padding:12px 14px;border-bottom:1px solid #1e2a4a33;cursor:pointer'; d.innerHTML=`<div style="width:32px;height:32px;border-radius:50%;background:#a5b4fc;color:#000;display:flex;align-items:center;justify-content:center;font-weight:700">${(c.nombre||c.id).slice(0,2).toUpperCase()}</div><div><div style="font-size:13px;font-weight:600">${c.nombre||c.id}</div><div style="font-size:11px;color:#94a3b8">${(c.mensajes?.slice(-1)[0]?.texto||'').slice(0,28)}</div></div>`; d.onclick=()=>openChat(c.id); list.appendChild(d);}); const pc=allChats.filter(c=>(c.tags||[]).some(t=>t.toLowerCase().includes('pendiente')||t.toLowerCase().includes('agendado'))).length; const cc=document.getElementById('calCount'); if(pc>0){cc.style.display='inline';cc.innerText=pc;} else cc.style.display='none';}
async function openChat(id){curChat=id; const r=await fetch('/api/mensajes/'+S.eid+'/'+id); const j=await r.json(); const prof=j.profile||{}; document.getElementById('hName').innerText=prof.nombre||id; document.getElementById('pAv').innerText=(prof.nombre||id).slice(0,2).toUpperCase(); document.getElementById('pPhone').innerText=id; document.getElementById('pNombre').value=prof.nombre||''; document.getElementById('pNameEdit').innerText=prof.nombre||id; document.getElementById('pCiudad').value=prof.ciudad||''; document.getElementById('pProfesion').value=prof.profesion||''; document.getElementById('pEmpresa').value=prof.empresa||''; document.getElementById('pEstado').value=prof.estado||'nuevo'; document.getElementById('pOrigen').value=prof.origen||''; document.getElementById('pCamp').value=prof.campana||''; document.getElementById('pNotes').value=(prof.notas||[]).map(n=>n.texto||n).join('\n')||''; document.getElementById('pTags').innerHTML=(prof.tags||[]).map(t=>`<span style="font-size:10px;padding:4px 8px;border-radius:20px;background:#1e293b;border:1px solid #2a3a5c;margin:2px;display:inline-flex">${t} <span style="cursor:pointer;margin-left:4px" onclick="removeTag('${t}')">✕</span></span>`).join(''); document.getElementById('msgs').innerHTML=j.mensajes.map(m=>`<div class="b ${m.from==='agente'?'age':'cli'}">${m.texto}${m.media_url?`<br><a href="${m.media_url}" target="_blank" style="color:#3b82f6">Ver archivo</a>`:''}<div style="font-size:10px;color:#64748b;text-align:right">${new Date(m.ts).toLocaleTimeString()}</div></div>`).join(''); fetch('/api/chat/leido',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({empresa_id:S.eid, chat_id:id})});}
async function sendMsg(){const t=document.getElementById('txt'); if(!t.value||!curChat) return; const txt=t.value; t.value=''; await fetch('/api/mensaje/enviar',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({empresa_id:S.eid,chat_id:curChat,texto:txt})}); openChat(curChat);}
function openApi(){clearMenu();document.getElementById('mConfig').classList.add('active');document.getElementById('mainFull').style.display='flex';document.querySelectorAll('.view').forEach(e=>e.style.display='none');document.getElementById('configView').style.display='flex';document.getElementById('apiModal').style.display='flex';loadApi();}
async function loadApi(){const role=S.user?.rol||'agente'; const r=await fetch('/api/config/'+S.eid+'?role='+role); const j=await r.json(); if(j.is_admin){apiPhone.value=j.config.phone||''; apiWaba.value=j.config.waba||''; apiToken.value=j.config.token||''; document.getElementById('apiCurrent').innerText=`Admin - Phone ${j.config.phone||''} - WABA ${j.config.waba||''} - Token ${j.config.token? j.config.token.slice(0,12)+'... OK - Acepta 1d 60d permanente' : 'no'}`; document.getElementById('apiAdminOnly').style.display='block';} else {document.getElementById('apiCurrent').innerText=`Trabajador - ${j.config.has_token?'API OK - plantillas heredadas - token acepta 1d 60d permanente':''}`; document.getElementById('apiAdminOnly').style.display='none';}}
async function loadConfigAndTemplates(){await loadApi(); await loadTemplates();}
async function saveApi(){if(S.user?.rol!=='admin') return alert('Solo admin'); await fetch('/api/config/api',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({empresa_id:S.eid, phone:apiPhone.value, waba:apiWaba.value, token:apiToken.value, admin_email:S.user.email})}); document.getElementById('apiMsg').innerText='✅ Guardado en base - acepta 1 día, 60 días y permanente'; await loadTemplates(); setTimeout(()=>{apiModal.style.display='none';},800);}
async function saveProfile(){if(!curChat) return; await fetch('/api/chat/profile',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({empresa_id:S.eid, chat_id:curChat, nombre:pNombre.value||pNameEdit.innerText, ciudad:pCiudad.value, profesion:pProfesion.value, empresa:pEmpresa.value, estado:pEstado.value, origen:pOrigen.value, campana:pCamp.value, notas:pNotes.value})});}
async function addTag(){if(!curChat) return; await fetch('/api/chat/tag/add',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({empresa_id:S.eid,chat_id:curChat,tag:newTag.value})}); newTag.value=''; openChat(curChat);}
async function removeTag(tag){await fetch('/api/chat/tag/remove',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({empresa_id:S.eid,chat_id:curChat,tag})}); openChat(curChat);}
async function agendarCliente(){if(!curChat) return; await fetch('/api/calendar/agendar',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({empresa_id:S.eid, chat_id:curChat, estado_agenda:pAgendaEstado.value, fecha:pAgendaFecha.value, nota:pAgendaNota.value})}); alert('Agendado'); loadCalendar();}
async function loadCalendar(){
  const [rCal, rTeam, rStats] = await Promise.all([fetch('/api/calendar/'+S.eid), fetch('/api/empresa/info/'+S.eid), fetch('/api/equipo/stats/'+S.eid)]);
  const cals = await rCal.json(); const info = await rTeam.json(); const stats = await rStats.json();
  const workers = info.usuarios||[]; const individuales = stats.individuales||[];
  const workersHtml = workers.map(u=>{
    const st = individuales.find(x=>x.email===u.email);
    return `<div class="teamCard" style="flex-direction:column;align-items:flex-start"><div style="width:100%;display:flex;justify-content:space-between"><div><b>👤 ${u.email}</b><br><span style="font-size:11px;color:#3b82f6;font-weight:700">${u.rol.toUpperCase()}</span><br><span style="font-size:11px;color:#94a3b8">Chats: ${st?.chats_atendidos||0} | Avance: ${st?.avance||0}% | Seguimiento: ${st?.seguimiento||0}</span></div><div style="text-align:right"><div style="background:#3b82f6;color:#fff;padding:4px 10px;border-radius:12px;font-size:11px;font-weight:700">${st?.seguimiento||0} citas</div></div></div></div>`;
  }).join('') || 'Sin trabajadores';
  const citasHtml = cals.length? cals.sort((a,b)=>new Date(a.date)-new Date(b.date)).map(c=>{
    const date = new Date(c.date).toLocaleString('es-CO', {dateStyle:'medium', timeStyle:'short'});
    const hechoStyle = c.hecho? 'opacity:0.6;border-color:#22c55e' : '';
    return `<div style="background:#1e293b;border:1px solid #2a3a5c;border-radius:12px;padding:14px;margin:10px 0;${hechoStyle}">
      <div style="display:flex;justify-content:space-between;align-items:start"><div style="flex:1"><div style="display:flex;gap:8px;align-items:center"><b style="font-size:14px">👤 ${c.chat_nombre||c.chat_id}</b><span style="background:${c.estado_agenda==='agendado'?'#3b82f6':'#f59e0b'};color:#fff;padding:2px 8px;border-radius:10px;font-size:10px">${(c.estado_agenda||'').toUpperCase()}</span>${c.hecho?'<span style="background:#22c55e;color:#000;padding:2px 8px;border-radius:10px;font-size:10px">HECHO</span>':''}</div>
      <div style="font-size:11px;color:#94a3b8;margin-top:6px;line-height:16px">📞 <b>${c.telefono||c.chat_id}</b> | 📅 <b>${date}</b><br>🏢 Empresa: ${c.empresa||'-'} | 🌎 Ciudad: ${c.ciudad||'-'} | 💼 Cargo: ${c.profesion||'-'}<br>📧 Email: ${c.email||'-'} | 🔖 Origen: ${c.origen||'-'} | 📢 Campaña: ${c.campana||'-'}<br>🏷️ Tags: ${(c.tags||[]).join(', ')||'-'}</div></div>
      <div style="display:flex;flex-direction:column;gap:6px"><button onclick="marcarHecho('${c.id}')" style="background:${c.hecho?'#1e293b':'#22c55e'};border:1px solid #2a3a5c;padding:6px 12px;border-radius:8px;color:${c.hecho?'#fff':'#000'};font-weight:700;font-size:11px;cursor:pointer">${c.hecho?'↩️ Deshacer':'✅ Hecho'}</button><button onclick="borrarCita('${c.id}')" style="background:#1e293b;border:1px solid #ef4444;color:#ef4444;padding:6px 12px;border-radius:8px;font-size:11px;cursor:pointer">🗑️ Borrar</button><button onclick="openChat('${c.chat_id}');showView('inbox')" style="background:#3b82f6;border:0;padding:6px 12px;border-radius:8px;color:#fff;font-size:11px;cursor:pointer">💬 Chat</button></div></div>
      <div style="margin-top:10px;background:#0b1020;padding:10px;border-radius:8px;border-left:3px solid #f59e0b"><div style="font-size:11px;color:#f59e0b;font-weight:700">📝 NOTA:</div><div style="font-size:12px;color:#e2e8f0;margin-top:4px">${c.nota||'Sin nota'}</div></div></div>`;
  }).join('') : '<div style="text-align:center;padding:40px;background:#131b2e;border:1px dashed #2a3a5c;border-radius:12px;color:#64748b"><div style="font-size:32px">📅</div><div>Sin citas - Agenda desde Customer Profile en Inbox</div></div>';
  document.getElementById('calList').innerHTML = `<div style="background:#131b2e;border:1px solid #1e2a4a;border-radius:14px;padding:16px;margin-bottom:16px"><h3 style="margin:0 0 12px;color:#3b82f6">👥 Trabajadores organizados (${workers.length})</h3><div style="display:grid;grid-template-columns:1fr 1fr;gap:12px">${workersHtml}</div></div><div style="background:#131b2e;border:1px solid #1e2a4a;border-radius:14px;padding:16px"><h3 style="margin:0 0 12px;color:#f59e0b">📅 Citas programadas con todos los datos (${cals.length}) - Pendientes: ${cals.filter(x=>!x.hecho).length} / Hechas: ${cals.filter(x=>x.hecho).length}</h3>${citasHtml}</div>`;
}
async function marcarHecho(id){ await fetch('/api/calendar/hecho',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({empresa_id:S.eid, id})}); loadCalendar(); }
async function borrarCita(id){ if(!confirm('¿Borrar cita?')) return; await fetch('/api/calendar/delete',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({empresa_id:S.eid, id})}); loadCalendar(); }
async function loadStatsGrafica(){const r=await fetch('/api/stats/'+S.eid); const s=await r.json(); const r2=await fetch('/api/equipo/stats/'+S.eid); const eq=await r2.json(); document.getElementById('sChats').innerText=s.chats||0; document.getElementById('sCals').innerText=s.calendar||0; document.getElementById('sSeg').innerText=s.calendar_pendientes||0; document.getElementById('sTeam').innerText=eq.individuales?.length||0; const labels=(eq.individuales||[]).map(i=>i.email.split('@')[0]); const chatsData=(eq.individuales||[]).map(i=>i.chats_atendidos||0); if(chart1) chart1.destroy(); chart1=new Chart(document.getElementById('chartTrabajador'),{type:'bar',data:{labels, datasets:[{label:'Chats por trabajador', data:chatsData, backgroundColor:'#3b82f6'}]},options:{responsive:true}}); const estados=await (await fetch('/api/metrics/'+S.eid)).json(); if(chart2) chart2.destroy(); chart2=new Chart(document.getElementById('chartEstado'),{type:'doughnut',data:{labels:Object.keys(estados.estados||{}), datasets:[{data:Object.values(estados.estados||{}), backgroundColor:['#3b82f6','#22c55e','#f59e0b','#ef4444']}]},options:{responsive:true}});}
async function loadMetricsWorkers(){const r=await fetch('/api/equipo/stats/'+S.eid); const j=await r.json(); const r2=await fetch('/api/metrics/'+S.eid); const m=await r2.json(); document.getElementById('metricsKpi').innerHTML=`<div class="kpiCard"><div style="font-size:11px">TOTAL</div><div style="font-size:20px;font-weight:800">${m.total_chats||0}</div></div><div class="kpiCard"><div style="font-size:11px">NO LEIDOS</div><div style="font-size:20px;font-weight:800">${m.no_leidos||0}</div></div><div class="kpiCard"><div style="font-size:11px">PENDIENTES</div><div style="font-size:20px;font-weight:800">${j.grupal?.recordatorios_pendientes||0}</div></div><div class="kpiCard"><div style="font-size:11px">CLIENTES</div><div style="font-size:20px;font-weight:800">${m.clientes||0}</div></div>`; document.getElementById('metricsWorkers').innerHTML=(j.individuales||[]).map(u=>`<div class="teamCard"><span>👤 ${u.email} - ${u.chats_atendidos} chats - Avance ${u.avance}% - Seg ${u.seguimiento} - Msj ${u.mensajes}</span></div>`).join(''); document.getElementById('metricsGeneral').innerHTML=`<div style="margin-top:12px;background:#1e293b;border:1px solid #2a3a5c;border-radius:12px;padding:12px">Grupal: ${j.grupal?.total_chats||0} total | ${j.grupal?.atendidos||0} atendidos (${j.grupal?.porcentaje||0}%) | Recordatorios: ${j.grupal?.total_recordatorios||0} | Hechos: ${j.grupal?.recordatorios_hechos||0}</div>`;}
async function loadTeam(){const r=await fetch('/api/empresa/info/'+S.eid); const info=await r.json(); document.getElementById('teamList').innerHTML=(info.usuarios||[]).map(u=>`<div class="teamCard"><span>${u.email} - ${u.rol}</span><button onclick="removeWorker('${u.email}')" style="background:#ef4444;border:0;padding:6px 10px;border-radius:8px;color:#fff">Eliminar</button></div>`).join('');}
async function addWorker(){const email=eqEmail.value.trim(); const pass=eqPass.value.trim(); if(!email||!pass) return alert('Email y pass'); const res=await fetch('/api/equipo/add',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({empresa_id:S.eid, email, pass, rol:eqRol.value})}); const j=await res.json(); if(!j.ok) alert(j.error||'Error'); loadTeam(); eqEmail.value=''; eqPass.value='';}
async function removeWorker(email){if(!confirm('Eliminar '+email+'?')) return; await fetch('/api/equipo/remove',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({empresa_id:S.eid, email})}); loadTeam();}
function elegirPlan(plan){localStorage.setItem('klido_plan',plan); document.getElementById('planBadge').innerText='Plan '+plan; alert('Plan '+plan+' seleccionado');}
function extractPhones(text){const regex=/(\+?\d[\d\s\-\(\)]{7,}\d)/g; const matches=text.match(regex)||[]; return [...new Set(matches.map(m=>m.replace(/\D/g,'')).filter(n=>n.length>=10 && n.length<=15).map(n=>{ let x=n.replace(/\D/g,''); if(x.length===10) x='57'+x; return x; }))];}
function extractEmails(text){const re=/[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}/g; return [...new Set((text.match(re)||[]))];}
function parseExcel(){const file=document.getElementById('excelFile').files[0]; if(!file) return; const reader=new FileReader(); reader.onload=function(e){const wb=XLSX.read(e.target.result,{type:'binary'}); let allText=''; wb.SheetNames.forEach(name=>{ const sheet=wb.Sheets[name]; const json=XLSX.utils.sheet_to_json(sheet,{header:1, defval:''}); json.forEach(row=>{ row.forEach(cell=>{ allText+=' '+String(cell); }); }); }); const tipo=document.getElementById('campTipo').value; excelNums=tipo==='gmail'?extractEmails(allText):extractPhones(allText); document.getElementById('excelResult').innerText=`Detectados ${excelNums.length}`; updateTotal();}; reader.readAsBinaryString(file);}
function parseManual(){const txt=document.getElementById('manualNums').value; const tipo=document.getElementById('campTipo').value; manualNums=tipo==='gmail'?extractEmails(txt):extractPhones(txt); document.getElementById('manualResult').innerText=`Detectados ${manualNums.length}`; updateTotal();}
function toggleTipo(){
  const tipo=document.getElementById('campTipo').value;
  const plan=(localStorage.getItem('klido_plan')||'basico').toLowerCase();
  const dbPlan=(S.user?.plan||plan);
  if(tipo==='gmail' && (plan!=='gold' && dbPlan!=='gold')){
    alert('⛔ Gmail masivo solo disponible en Plan Gold. Tu plan actual: '+plan+' - WhatsApp funciona en Básico.');
    document.getElementById('campTipo').value='whatsapp';
    document.getElementById('whatsappBlock').style.display='block';
    document.getElementById('gmailBlock').style.display='none';
    return;
  }
  parseExcel();parseManual();
  document.getElementById('whatsappBlock').style.display=tipo==='whatsapp'?'block':'none';
  document.getElementById('gmailBlock').style.display=tipo==='gmail'?'block':'none';
}
function updateTotal(){const all=[...excelNums,...manualNums]; const uniq=[...new Set(all)]; detected=uniq; document.getElementById('totalNums').innerText=`${uniq.length} contactos - 50 cada 4h anti-baneo`;}
async function loadTemplates(){
  const sel=document.getElementById('campTemplate');
  const info=document.getElementById('templateInfo');
  sel.innerHTML='<option>Cargando plantillas aprobadas...</option>';
  info.innerHTML='Consultando Meta Graph... acepta 1 día 60 días permanente';
  try{
    const r=await fetch('/api/templates/'+S.eid);
    const j=await r.json();
    console.log('TEMPLATES V240:', j);
    templates=j.templates||[];

    let html='';
    if(j.error){
      html+=`<div style="background:#ef444433;border:1px solid #ef4444;padding:8px;border-radius:8px;margin-bottom:6px">❌ ${j.error}<br>Cache: ${j.cached_count||0} | WABA: ${j.debug?.waba||'?'} | Phone: ${j.debug?.phone||'?'}<br>Código: ${j.debug?.error_code||''}</div>`;
    }
    if(j.warning){
      html+=`<div style="background:${j.approved>0?'#22c55e22':'#f59e0b22'};border:1px solid ${j.approved>0?'#22c55e':'#f59e0b'};padding:8px;border-radius:8px;margin-bottom:6px">${j.warning}<br><b>Token:</b> ${j.token_type||'aceptado'} | Total Meta: ${j.all||0} | Aprobadas: ${j.approved||0}</div>`;
    }
    info.innerHTML=html || `✅ ${templates.length} plantillas`;

    if(templates.length===0){
      sel.innerHTML=`<option value="">No hay aprobadas - Total Meta: ${j.all||0} - Cache: ${j.cached_count||0} - Revisa WABA ID (no Business ID)</option>`;
      document.getElementById('varBlock').innerHTML=`<div style="font-size:11px;color:#f59e0b;background:#0b1020;padding:8px;border-radius:8px">Para fix foto "No hay aprobadas": 1) WABA ID correcto (empieza 10...) no Business ID 2) Token con permiso whatsapp_business_management 3) Plantillas APPROVED en business.facebook.com > WhatsApp Manager > Plantillas<br>Si ya tienes APPROVED, dale Recargar. Cache: ${j.cached_count||0}</div>`;
      return;
    }

    sel.innerHTML=templates.map(t=>`<option value="${t.name}">${t.name} - ${t.language} - ${t.status}</option>`).join('');
    onTemplateChange();
  }catch(e){
    sel.innerHTML=`<option>Error fetch</option>`;
    info.innerHTML=`Error: ${e.message} - Revisa /api/templates/${S.eid}`;
  }
}
function onTemplateChange(){const name=document.getElementById('campTemplate').value; const t=templates.find(x=>x.name===name); if(!t){document.getElementById('varBlock').innerHTML='<div style="font-size:11px;color:#94a3b8">Selecciona plantilla aprobada - acepta token 1 día 60 días permanente</div>'; return;} let varCount=0; const body=t.components?.find(c=>c.type==='BODY'); if(body && body.text){ const m=body.text.match(/\{\{\d+\}\}/g); if(m) varCount=m.length; } let html=`<div style="font-size:11px;color:#22c55e;margin-bottom:6px">📝 Plantilla: ${t.name} - Variables detectadas: ${varCount}</div>`; const header=t.components?.find(c=>c.type==='HEADER'); if(header?.format==='IMAGE'){ html+=`<label style="font-size:10px">Header Imagen URL</label><input id="headerImage" class="api-input" placeholder="https://...imagen.jpg">`; } if(varCount>0){ for(let i=1;i<=varCount;i++){ html+=`<label style="font-size:10px">Variable {{${i}}}</label><input id="var${i}" class="api-input" placeholder="Valor para {{${i}}}">`; } } else { html+=`<div style="font-size:11px;color:#94a3b8">Sin variables - lista para enviar 50 cada 4h</div>`; } document.getElementById('varBlock').innerHTML=html;}
async function crearCamp(){if(detected.length===0) return alert('Sube numeros Excel o Manual'); const nombre=document.getElementById('campNombre').value.trim()||'Campaña '+(new Date().toLocaleDateString()); const tipo=document.getElementById('campTipo').value; const template=document.getElementById('campTemplate').value; if(tipo==='whatsapp' &&!template) return alert('Selecciona plantilla aprobada - si dice No hay aprobadas, revisa WABA ID y token'); const vars=[]; document.querySelectorAll('[id^="var"]').forEach(el=>{ if(el.id.startsWith('var')) vars.push(el.value); }); const body={empresa_id:S.eid, nombre, tipo, numeros:detected, template_name:template, template_lang:(templates.find(t=>t.name===template)?.language||'es'), variables:vars, header_image:document.getElementById('headerImage')?.value||'', gmail_subject:document.getElementById('gmailSubject')?.value||'', gmail_body:document.getElementById('gmailBody')?.value||''}; const r=await fetch('/api/campaigns/create',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}); const j=await r.json(); if(j.ok){ alert('✅ Campaña creada: '+nombre+' - '+detected.length+' contactos - 50 cada 4h - Pausar/Continuar disponible en historial'); detected=[]; excelNums=[]; manualNums=[]; document.getElementById('manualNums').value=''; document.getElementById('excelResult').innerText=''; document.getElementById('manualResult').innerText=''; updateTotal(); loadCampHistory(); } else alert('❌ '+ (j.error||'Error'));}
async function loadCampHistory(){const r=await fetch('/api/campaigns/'+S.eid); const j=await r.json(); const list=j.campaigns||[]; if(list.length===0){ document.getElementById('campHistory').innerHTML='<div style="color:#64748b;font-size:12px;padding:10px">Sin campañas - Crea una arriba - Historial con Pausar/Continuar y seguimiento 50 cada 4h</div>'; return; } document.getElementById('campHistory').innerHTML=list.map(c=>`<div class="teamCard"><div><b>🔔 ${c.nombre}</b> - ${c.tipo.toUpperCase()}<br><span style="font-size:11px">${c.template_name||c.gmail_subject||''} | ${c.enviados||0}/${c.total} enviados | ${c.fallidos||0} fallidos | Estado: <b style="color:${c.status==='running'?'#22c55e': c.status==='paused'?'#f59e0b':'#94a3b8'}">${c.status.toUpperCase()}</b></span><br><span style="font-size:10px;color:#64748b">Creado: ${new Date(c.creado).toLocaleString()} | Próximo lote: ${c.next_send? new Date(c.next_send).toLocaleString() : 'Ahora'}</span></div><div style="display:flex;gap:6px"><button onclick="pauseCamp('${c.id}')" style="background:${c.status==='paused'?'#22c55e':'#f59e0b'};border:0;padding:6px 12px;border-radius:8px;color:${c.status==='paused'?'#fff':'#000'};font-weight:700;font-size:11px">${c.status==='paused'?'▶️ Continuar':'⏸️ Pausar'}</button><button onclick="delCamp('${c.id}')" style="background:#1e293b;border:1px solid #ef4444;color:#ef4444;padding:6px 10px;border-radius:8px;font-size:11px">🗑️ Eliminar</button></div></div>`).join('');}
async function pauseCamp(id){await fetch('/api/campaigns/toggle',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({empresa_id:S.eid, id})}); loadCampHistory();}
async function delCamp(id){if(!confirm('¿Eliminar campaña?')) return; await fetch('/api/campaigns/delete',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({empresa_id:S.eid, id})}); loadCampHistory();}
init();
</script></body></html>
