// KLIDO v137 FINAL PRO + GERENTE GENERAL - TODO COMPLETO
import express from 'express'; import cors from 'cors'; import pg from 'pg'; import jwt from 'jsonwebtoken'; import bcrypt from 'bcryptjs'; import path from 'path'; import { fileURLToPath } from 'url'; import * as XLSX from 'xlsx'; import http from 'http'; import { Server } from 'socket.io';
const __filename=fileURLToPath(import.meta.url); const __dirname=path.dirname(__filename);
const app=express(); const server=http.createServer(app); const io=new Server(server,{cors:{origin:"*", methods:["GET","POST"]}});
app.use(cors({origin:"*"})); app.use(express.json({limit:'100mb'})); app.use(express.static(path.join(__dirname,'public')));
const {Pool}=pg; const pgPool=new Pool({connectionString:process.env.DATABASE_URL, ssl:{rejectUnauthorized:false}});
const JWT=process.env.JWT_SECRET||'klido-v137-gerente-final'; const GERENTE_CLAVE='klido123'; const GERENTE_LINK='/gerente-klido-3133181851';
const PHONE_ENV=process.env.PHONE_NUMBER_ID||''; const WABA_ENV=process.env.WABA_ID||''; let TOKEN_ENV=process.env.META_TOKEN||''; if(!TOKEN_ENV){ for(const v of Object.values(process.env)){ if(typeof v==='string'&&v.startsWith('EAAT')&&v.length>80){TOKEN_ENV=v;break;}}}

async function initDB(){
await pgPool.query(`CREATE TABLE IF NOT EXISTS agencias (id TEXT PRIMARY KEY, nombre TEXT, email TEXT UNIQUE, password TEXT, plan TEXT DEFAULT 'basico', plan_activo BOOLEAN DEFAULT true, phone_id TEXT, waba_id TEXT, meta_token TEXT, creado BIGINT, limite_usado INT DEFAULT 0, mantenimiento BIGINT, anual_vence BIGINT, api_status TEXT DEFAULT 'pendiente')`);
await pgPool.query(`CREATE TABLE IF NOT EXISTS clientes_klido (id TEXT PRIMARY KEY, agencia_id TEXT, telefono TEXT, nombre TEXT, email TEXT, datos JSONB DEFAULT '{}', recordatorio TIMESTAMP, etiqueta TEXT DEFAULT 'Nuevo', estado_embudo TEXT DEFAULT 'Nuevo', asesor_id TEXT, ultimo_mensaje TIMESTAMP DEFAULT NOW(), origen TEXT DEFAULT 'manual', no_leido INT DEFAULT 0, notas TEXT)`);
await pgPool.query(`CREATE TABLE IF NOT EXISTS mensajes_klido (id SERIAL PRIMARY KEY, agencia_id TEXT, cliente_id TEXT, telefono TEXT, tipo TEXT, contenido TEXT, url TEXT, timestamp BIGINT, direccion TEXT, mime TEXT, media_id TEXT)`);
await pgPool.query(`CREATE TABLE IF NOT EXISTS campanas_klido (id TEXT PRIMARY KEY, agencia_id TEXT, nombre TEXT, plantilla TEXT, tipo TEXT DEFAULT 'whatsapp', total INT, enviados INT DEFAULT 0, fallidos INT DEFAULT 0, estado TEXT DEFAULT 'activa', pausada BOOLEAN DEFAULT false, historial JSONB DEFAULT '[]', creada BIGINT, terminada BIGINT, numeros JSONB DEFAULT '[]', bloque_actual INT DEFAULT 0, programada BIGINT)`);
await pgPool.query(`CREATE TABLE IF NOT EXISTS campanas_gmail (id TEXT PRIMARY KEY, agencia_id TEXT, asunto TEXT, cuerpo TEXT, total INT, enviados INT DEFAULT 0, fallidos INT DEFAULT 0, estado TEXT DEFAULT 'activa', creada BIGINT)`);
await pgPool.query(`CREATE TABLE IF NOT EXISTS asesores (id TEXT PRIMARY KEY, agencia_id TEXT, nombre TEXT, telefono TEXT, email TEXT, activo BOOLEAN DEFAULT true, rol TEXT DEFAULT 'worker', password TEXT)`);
await pgPool.query(`CREATE TABLE IF NOT EXISTS soporte_klido (id SERIAL PRIMARY KEY, agencia_id TEXT, mensaje TEXT, fecha BIGINT)`);
console.log('✅ V137 GERENTE - DB OK');
} initDB();

function auth(req,res,next){ const h=req.headers.authorization; if(!h) return res.status(401).json({error:'No token'}); try{ req.user=jwt.verify(h.replace('Bearer ',''),JWT); next(); }catch{ res.status(401).json({error:'Token invalido'}); }}
function authGerente(req,res,next){ const k=req.headers['x-gerente-clave']||req.query.clave; if(k!==GERENTE_CLAVE) return res.status(401).json({error:'Clave gerente mala'}); next(); }
async function getEmp(id){ const {rows}=await pgPool.query('SELECT * FROM agencias WHERE id=$1',[id]); const r=rows[0]; if(!r) return null; return {id:r.id, phone:r.phone_id||PHONE_ENV, waba:r.waba_id||WABA_ENV, token:r.meta_token||TOKEN_ENV, plan:r.plan, nombre:r.nombre}; }
function normalizaNumeros(arr){ let out=[]; arr.forEach(raw=>{ String(raw||'').split(/[,;\n|]+/).forEach(p=>{ let d=p.replace(/\D/g,''); if(d.endsWith('.0')) d=d.slice(0,-2); if(d.length===10&&d.startsWith('3')) d='57'+d; if(d.length===12&&d.startsWith('57')) out.push(d); if(d.length>12){ const m=d.match(/3\d{9}/g); if(m) m.forEach(x=>out.push('57'+x)); } }); }); return [...new Set(out)].filter(n=>/^57[3]\d{9}$/.test(n)); }
function extraeEmails(arr){ let out=[]; const re=/[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}/g; arr.forEach(raw=>{ const ms=String(raw).match(re); if(ms) out.push(...ms); }); return [...new Set(out.map(e=>e.toLowerCase()))]; }
async function enviarMailResend(para,asunto,html){ const KEY=process.env.RESEND_API_KEY; if(!KEY) throw new Error('Falta RESEND_API_KEY'); await fetch('https://api.resend.com/emails',{method:'POST',headers:{'Authorization':`Bearer ${KEY}`,'Content-Type':'application/json'},body:JSON.stringify({from:'KLIDO <soporte@klidoapp.com.co>',to:para,subject:asunto,html})}); }

// LOGIN INTACTO
app.post('/api/auth/login',async(req,res)=>{ try{ const {email,password}=req.body; const {rows}=await pgPool.query('SELECT * FROM agencias WHERE email=$1',[email]); if(!rows[0]){ const {rows:as}=await pgPool.query('SELECT * FROM asesores WHERE email=$1',[email]); if(!as[0]) return res.status(404).json({error:'No existe'}); if(!await bcrypt.compare(password,as[0].password||'')) return res.status(401).json({error:'Clave mala'}); return res.json({ok:true,token:jwt.sign({agenciaId:as[0].agencia_id, asesorId:as[0].id, rol:'worker'},JWT), rol:'worker'}); } if(!await bcrypt.compare(password,rows[0].password)) return res.status(401).json({error:'Clave mala'}); if(!rows[0].plan_activo) return res.status(403).json({error:'Agencia bloqueada por Gerente'}); res.json({ok:true,token:jwt.sign({agenciaId:rows[0].id, rol:'admin'},JWT), rol:'admin'}); }catch(e){ res.status(500).json({error:e.message}); }});

// CONFIG API UNA SOLA VEZ
app.get('/api/config',auth,async(req,res)=>{ const emp=await getEmp(req.user.agenciaId); res.json({phoneId:emp.phone, wabaId:emp.waba, tieneToken:emp.token.length>50, plan:emp.plan}); });
app.post('/api/config',auth,async(req,res)=>{ const {phoneId,wabaId,metaToken}=req.body; await pgPool.query('UPDATE agencias SET phone_id=$1,waba_id=$2,meta_token=$3,api_status=$4 WHERE id=$5',[phoneId,wabaId,metaToken,'conectado',req.user.agenciaId]); res.json({ok:true}); });
app.get('/api/config-info',(req,res)=>res.json({que:'CRM Oficial', premium:'IA + Pasar a humano', gold:'IA + Llamadas + Gmail', wa:'https://wa.me/573133181851'}));
app.get('/api/planes',(req,res)=>res.json([{id:'basico',nombre:'BÁSICO',anual:800000,trimestral:80000},{id:'premium',nombre:'PREMIUM + IA',anual:1300000,trimestral:95000},{id:'gold',nombre:'GOLD TOTAL',anual:2400000,trimestral:120000}]));
app.get('/api/plantillas',auth,async(req,res)=>{ const emp=await getEmp(req.user.agenciaId); try{ const r=await fetch(`https://graph.facebook.com/v20.0/${emp.waba}/message_templates?access_token=${emp.token}&limit=250`); const j=await r.json(); res.json((j.data||[]).filter(t=>t.status==='APPROVED')); }catch{ res.json([]); }});

// BANDEJA
app.get('/api/clientes',auth,async(req,res)=>{ const {filtro,buscar}=req.query; let q=`SELECT * FROM clientes_klido WHERE agencia_id=$1`; let p=[req.user.agenciaId]; if(req.user.rol==='worker'){ q+=` AND asesor_id=$2`; p=[req.user.agenciaId, req.user.asesorId]; } if(filtro==='no_leidos') q+=` AND no_leido>0`; if(filtro==='campana') q+=` AND origen='campana'`; if(buscar){ q+=` AND (telefono ILIKE $${p.length+1} OR nombre ILIKE $${p.length+1})`; p.push(`%${buscar}%`); } q+=` ORDER BY ultimo_mensaje DESC LIMIT 300`; const {rows}=await pgPool.query(q,p); res.json(rows); });
app.get('/api/mensajes/:clienteId',auth,async(req,res)=>{ const {rows}=await pgPool.query('SELECT * FROM mensajes_klido WHERE cliente_id=$1 ORDER BY timestamp ASC LIMIT 1000',[req.params.clienteId]); res.json(rows); });
app.post('/api/mensajes/:clienteId',auth,async(req,res)=>{ const {contenido}=req.body; const {rows:cl}=await pgPool.query('SELECT telefono FROM clientes_klido WHERE id=$1',[req.params.clienteId]); const emp=await getEmp(req.user.agenciaId); try{ await fetch(`https://graph.facebook.com/v20.0/${emp.phone}/messages`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${emp.token}`},body:JSON.stringify({messaging_product:'whatsapp',to:cl[0].telefono,type:'text',text:{body:contenido}})}); }catch{} await pgPool.query('INSERT INTO mensajes_klido (agencia_id,cliente_id,telefono,tipo,contenido,timestamp,direccion) VALUES ($1,$2,$3,$4,$5,$6,$7)',[req.user.agenciaId,req.params.clienteId,cl[0].telefono,'text',contenido,Date.now(),'saliente']); io.emit('new_message',{agencia_id:req.user.agenciaId}); res.json({ok:true}); });
app.post('/api/clientes/:id/datos',auth,async(req,res)=>{ const {etiqueta,embudo,asesor,notas,recordatorio,nombre}=req.body; await pgPool.query(`UPDATE clientes_klido SET etiqueta=COALESCE($1,etiqueta), estado_embudo=COALESCE($2,estado_embudo), asesor_id=COALESCE($3,asesor_id), notas=COALESCE($4,notas), recordatorio=COALESCE($5,recordatorio), nombre=COALESCE($6,nombre) WHERE id=$7`,[etiqueta,embudo,asesor,notas,recordatorio?new Date(recordatorio):null,nombre,req.params.id]); res.json({ok:true}); });
app.get('/api/recordatorios',auth,async(req,res)=>{ const {rows}=await pgPool.query('SELECT * FROM clientes_klido WHERE agencia_id=$1 AND recordatorio IS NOT NULL ORDER BY recordatorio ASC',[req.user.agenciaId]); res.json(rows); });

// CAMPAÑAS WPP + GMAIL
app.post('/api/campanas/parse-excel',auth,async(req,res)=>{ const {dataBase64}=req.body; const buffer=Buffer.from(dataBase64.split(',').pop(),'base64'); const wb=XLSX.read(buffer,{type:'buffer'}); let nums=[], emails=[]; wb.SheetNames.forEach(n=>{ const ws=wb.Sheets[n]; const json=XLSX.utils.sheet_to_json(ws,{header:1,defval:''}); json.forEach(r=>{ r.forEach(c=>{ nums.push(...normalizaNumeros([String(c)])); emails.push(...extraeEmails([String(c)])); }); }); }); res.json({ok:true, numeros:[...new Set(nums)], emails:[...new Set(emails)], total:nums.length, totalEmails:emails.length}); });
async function getMeta(p,emp){ try{ const r=await fetch(`https://graph.facebook.com/v20.0/${emp.waba}/message_templates?access_token=${emp.token}&limit=250`); const j=await r.json(); const t=j.data?.find(x=>x.name===p); if(!t) return null; let v=[]; (t.components||[]).forEach(c=>{ if(c.text){ [...c.text.matchAll(/\{\{([^}]+)\}\}/g)].forEach(m=>v.push(m[1].trim())); } }); return {language:t.language,varNames:v}; }catch{ return null; }}
async function procesaWPP(id){ const {rows}=await pgPool.query('SELECT * FROM campanas_klido WHERE id=$1',[id]); if(!rows[0]) return; let c=rows[0]; if(c.programada && c.programada>Date.now()){ setTimeout(()=>procesaWPP(id), c.programada-Date.now()); return; } let nums=c.numeros; if(typeof nums==='string') nums=JSON.parse(nums); nums=normalizaNumeros(nums); const emp=await getEmp(c.agencia_id); const meta=await getMeta(c.plantilla, emp); if(!meta) return; let vars=[]; try{ const h=typeof c.historial==='string'?JSON.parse(c.historial):c.historial; vars=h?.[0]?.variables||[]; }catch{} if(vars.length<meta.varNames.length) while(vars.length<meta.varNames.length) vars.push('Cliente'); const isNamed=meta.varNames.length>0 && isNaN(parseInt(meta.varNames[0])); const pn={name:c.plantilla, language:{code:meta.language||'es_CO'}, components:[{type:'body', parameters: meta.varNames.map((n,i)=>({type:'text', text:String(vars[i]||'Cliente').slice(0,100), parameter_name:n}))}]}; const pnum={name:c.plantilla, language:{code:meta.language||'es_CO'}, components:[{type:'body', parameters: vars.map(v=>({type:'text', text:String(v).slice(0,100)}))}]}; const atts=isNamed?[pn,pnum]:[pnum,pn]; for(let i=c.bloque_actual||0;i<nums.length;i++){ const {rows:st}=await pgPool.query('SELECT pausada FROM campanas_klido WHERE id=$1',[id]); if(st[0]?.pausada){ await pgPool.query('UPDATE campanas_klido SET bloque_actual=$1 WHERE id=$2',[i,id]); return; } let ok=false; for(const att of atts){ try{ const r=await fetch(`https://graph.facebook.com/v20.0/${emp.phone}/messages`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${emp.token}`},body:JSON.stringify({messaging_product:'whatsapp',to:nums[i],type:'template',template:att})}); const j=await r.json(); if(j.error) throw j.error; await pgPool.query('UPDATE campanas_klido SET enviados=enviados+1, bloque_actual=$1 WHERE id=$2',[i+1,id]); ok=true; io.emit('campana_update',{id, enviados:i+1}); break; }catch{} } if(!ok) await pgPool.query('UPDATE campanas_klido SET fallidos=fallidos+1 WHERE id=$1',[id]); await new Promise(r=>setTimeout(r,1500)); } await pgPool.query('UPDATE campanas_klido SET estado=$1,terminada=$2 WHERE id=$3',['terminada',Date.now(),id]); }
app.post('/api/campanas',auth,async(req,res)=>{ const {nombre,plantilla,numeros,variables,programada}=req.body; const id='camp_'+Date.now(); const prog=programada?new Date(programada).getTime():null; await pgPool.query('INSERT INTO campanas_klido (id,agencia_id,nombre,plantilla,total,creada,historial,numeros,programada) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)',[id,req.user.agenciaId,nombre||plantilla,plantilla,normalizaNumeros(numeros).length,Date.now(),JSON.stringify([{variables}]),JSON.stringify(normalizaNumeros(numeros)),prog]); if(!prog) procesaWPP(id); else setTimeout(()=>procesaWPP(id), prog-Date.now()); res.json({ok:true,id}); });
app.get('/api/campanas',auth,async(req,res)=>{ const {rows}=await pgPool.query('SELECT * FROM campanas_klido WHERE agencia_id=$1 ORDER BY creada DESC',[req.user.agenciaId]); res.json(rows); });
app.post('/api/campanas/:id/pausa',auth,async(req,res)=>{ await pgPool.query('UPDATE campanas_klido SET pausada=true WHERE id=$1',[req.params.id]); res.json({ok:true}); });
app.post('/api/campanas/:id/continuar',auth,async(req,res)=>{ await pgPool.query('UPDATE campanas_klido SET pausada=false WHERE id=$1',[req.params.id]); procesaWPP(req.params.id); res.json({ok:true}); });
app.post('/api/campanas/gmail',auth,async(req,res)=>{ const {asunto,cuerpo,emails}=req.body; const id='gmail_'+Date.now(); const vals=extraeEmails(emails); await pgPool.query('INSERT INTO campanas_gmail (id,agencia_id,asunto,cuerpo,total,creada) VALUES ($1,$2,$3,$4,$5,$6)',[id,req.user.agenciaId,asunto,cuerpo,vals.length,Date.now()]); (async()=>{ for(const e of vals){ try{ await enviarMailResend(e,asunto,cuerpo); await pgPool.query('UPDATE campanas_gmail SET enviados=enviados+1 WHERE id=$1',[id]); }catch{ await pgPool.query('UPDATE campanas_gmail SET fallidos=fallidos+1 WHERE id=$1',[id]); } await new Promise(r=>setTimeout(r,800)); } })(); res.json({ok:true,id,total:vals.length}); });
app.get('/api/campanas/gmail',auth,async(req,res)=>{ const {rows}=await pgPool.query('SELECT * FROM campanas_gmail WHERE agencia_id=$1 ORDER BY creada DESC',[req.user.agenciaId]); res.json(rows); });
app.get('/api/trabajadores',auth,async(req,res)=>{ const {rows}=await pgPool.query('SELECT * FROM asesores WHERE agencia_id=$1',[req.user.agenciaId]); res.json(rows); });
app.post('/api/trabajadores',auth,async(req,res)=>{ const id='as_'+Date.now(); const hash=await bcrypt.hash(req.body.password||'123456',10); await pgPool.query('INSERT INTO asesores (id,agencia_id,nombre,email,telefono,password) VALUES ($1,$2,$3,$4,$5,$6)',[id,req.user.agenciaId,req.body.nombre,req.body.email,req.body.telefono,hash]); res.json({ok:true}); });
app.delete('/api/trabajadores/:id',auth,async(req,res)=>{ await pgPool.query('DELETE FROM asesores WHERE id=$1',[req.params.id]); res.json({ok:true}); });
app.get('/api/dashboard',auth,async(req,res)=>{ const c=await pgPool.query('SELECT COUNT(*) FROM clientes_klido WHERE agencia_id=$1',[req.user.agenciaId]); const m=await pgPool.query('SELECT COUNT(*) FROM mensajes_klido WHERE agencia_id=$1',[req.user.agenciaId]); res.json({clientes:c.rows[0].count, mensajes:m.rows[0].count}); });
app.post('/api/soporte',auth,async(req,res)=>{ await pgPool.query('INSERT INTO soporte_klido (agencia_id,mensaje,fecha) VALUES ($1,$2,$3)',[req.user.agenciaId,req.body.mensaje,Date.now()]); res.json({ok:true, wa:`https://wa.me/573133181851?text=${encodeURIComponent(req.body.mensaje)}`}); });

// --- PANEL GERENTE GENERAL - LINK APARTE ---
app.get(GERENTE_LINK,(req,res)=>{
  res.send(`<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Gerente General KLIDO</title><style>body{font-family:Inter,sans-serif;background:#0A1931;color:#fff;margin:0;padding:20px}h1{color:#3B82F6}.card{background:#132A53;padding:15px;border-radius:12px;margin:10px 0;display:flex;justify-content:space-between;align-items:center}.btn{padding:8px 12px;border-radius:8px;border:0;cursor:pointer;font-weight:bold}.bloquear{background:#EF4444;color:#fff}.desbloquear{background:#10B981;color:#fff}.plan{background:#3B82F6;color:#fff}input,select{padding:8px;border-radius:8px;border:0;margin:2px}</style></head><body>
  <h1>🔐 Gerente General KLIDO - 3133181851</h1>
  <div><input id="clave" type="password" placeholder="Clave gerente klido123"><button class="btn plan" onclick="login()">Entrar</button></div>
  <div id="panel" style="display:none"><h2>Agencias</h2><div id="lista"></div></div>
  <script>
  let CLAVE=''; function login(){ CLAVE=document.getElementById('clave').value; if(CLAVE!=='klido123'){ alert('Clave mala'); return; } document.getElementById('panel').style.display='block'; cargar(); }
  async function cargar(){ const r=await fetch('/api/superadmin/agencias',{headers:{'x-gerente-clave':CLAVE}}); const j=await r.json(); const div=document.getElementById('lista'); div.innerHTML=''; j.forEach(a=>{ div.innerHTML+=\`<div class="card"><div><b>\${a.nombre}</b> (\${a.email})<br>Plan: \${a.plan} | Usados: \${a.limite_usado} | Clientes: \${a.total_clientes} | Mensajes: \${a.total_mensajes} | Trabajadores: \${a.total_trabajadores} | Estado: \${a.plan_activo?'✅ Activo':'🔴 Bloqueado'}<br>Creado: \${new Date(Number(a.creado)).toLocaleDateString()} | Vence: \${a.anual_vence?new Date(Number(a.anual_vence)).toLocaleDateString():'-'}</div><div><button class="btn \${a.plan_activo?'bloquear':'desbloquear'}" onclick="toggle('\${a.id}',\${a.plan_activo})">\${a.plan_activo?'Bloquear':'Desbloquear'}</button> <select onchange="cambiarPlan('\${a.id}',this.value)"><option value="">Cambiar plan</option><option value="basico">Básico</option><option value="premium">Premium</option><option value="gold">Gold</option></select> <button class="btn plan" onclick="verTrab('\${a.id}')">Ver equipo</button></div></div>\`; }); }
  async function toggle(id,activo){ await fetch('/api/superadmin/agencias/'+id+'/'+(activo?'bloquear':'desbloquear'),{method:'POST',headers:{'x-gerente-clave':CLAVE}}); cargar(); }
  async function cambiarPlan(id,plan){ if(!plan) return; await fetch('/api/superadmin/agencias/'+id+'/plan',{method:'POST',headers:{'Content-Type':'application/json','x-gerente-clave':CLAVE},body:JSON.stringify({plan})}); cargar(); }
  async function verTrab(id){ const r=await fetch('/api/superadmin/agencias/'+id+'/trabajadores',{headers:{'x-gerente-clave':CLAVE}}); const j=await r.json(); alert('Trabajadores: '+JSON.stringify(j,null,2)); }
  </script></body></html>`);
});

app.get('/api/superadmin/agencias',authGerente,async(req,res)=>{
  const {rows}=await pgPool.query(`SELECT a.*, (SELECT COUNT(*) FROM clientes_klido c WHERE c.agencia_id=a.id) as total_clientes, (SELECT COUNT(*) FROM mensajes_klido m WHERE m.agencia_id=a.id) as total_mensajes, (SELECT COUNT(*) FROM asesores t WHERE t.agencia_id=a.id) as total_trabajadores FROM agencias a ORDER BY a.creado DESC`);
  res.json(rows);
});
app.post('/api/superadmin/agencias/:id/bloquear',authGerente,async(req,res)=>{ await pgPool.query('UPDATE agencias SET plan_activo=false WHERE id=$1',[req.params.id]); res.json({ok:true}); });
app.post('/api/superadmin/agencias/:id/desbloquear',authGerente,async(req,res)=>{ await pgPool.query('UPDATE agencias SET plan_activo=true WHERE id=$1',[req.params.id]); res.json({ok:true}); });
app.post('/api/superadmin/agencias/:id/plan',authGerente,async(req,res)=>{ await pgPool.query('UPDATE agencias SET plan=$1 WHERE id=$2',[req.body.plan, req.params.id]); res.json({ok:true}); });
app.get('/api/superadmin/agencias/:id/trabajadores',authGerente,async(req,res)=>{ const {rows}=await pgPool.query('SELECT * FROM asesores WHERE agencia_id=$1',[req.params.id]); res.json(rows); });
app.get('/api/superadmin/metricas',authGerente,async(req,res)=>{ const totA=await pgPool.query('SELECT COUNT(*) FROM agencias'); const totC=await pgPool.query('SELECT COUNT(*) FROM clientes_klido'); const totM=await pgPool.query('SELECT COUNT(*) FROM mensajes_klido'); const totCamp=await pgPool.query('SELECT COUNT(*) FROM campanas_klido'); res.json({agencias:totA.rows[0].count, clientes:totC.rows[0].count, mensajes:totM.rows[0].count, campanas:totCamp.rows[0].count}); });

// WEBHOOK klido123 MULTI-EMPRESA INDIVIDUAL
app.get('/webhook',(req,res)=>{ if(req.query['hub.verify_token']==='klido123'){ console.log('✅ Webhook klido123 verificado'); return res.send(req.query['hub.challenge']); } return res.sendStatus(403); });
app.post('/webhook',async(req,res)=>{ res.sendStatus(200); try{ const v=req.body.entry?.[0]?.changes?.[0]?.value; const msg=v?.messages?.[0]; const contact=v?.contacts?.[0]; const meta=v?.metadata; if(!msg) return; const from=msg.from; const phoneId=meta?.phone_number_id; const {rows:ags}=await pgPool.query('SELECT id FROM agencias WHERE phone_id=$1',[phoneId]); const agenciaId=ags[0]?.id|| (await pgPool.query('SELECT id FROM agencias LIMIT 1')).rows[0]?.id; if(!agenciaId) return; const tipo=msg.type; let cont= tipo==='text'?msg.text?.body:`[${tipo}]`; const cid=`cli_${agenciaId}_${from}`; const {rows:ex}=await pgPool.query('SELECT id FROM clientes_klido WHERE telefono=$1 AND agencia_id=$2',[from,agenciaId]); if(!ex[0]) await pgPool.query('INSERT INTO clientes_klido (id,agencia_id,telefono,nombre,origen,no_leido) VALUES ($1,$2,$3,$4,$5,1)',[cid,agenciaId,from,contact?.profile?.name||from,'manual']); else await pgPool.query('UPDATE clientes_klido SET no_leido=no_leido+1, ultimo_mensaje=NOW() WHERE telefono=$1 AND agencia_id=$2',[from,agenciaId]); await pgPool.query('INSERT INTO mensajes_klido (agencia_id,cliente_id,telefono,tipo,contenido,media_id,timestamp,direccion) VALUES ($1,$2,$3,$4,$5,$6,$7,$8)',[agenciaId,cid,from,tipo,cont,msg[tipo]?.id||'',Date.now(),'entrante']); io.to(`agencia_${agenciaId}`).emit('new_message',{agencia_id:agenciaId}); io.emit('new_message',{agencia_id:agenciaId}); }catch(e){ console.log(e.message); }});
app.get('/api/media/:mediaId',auth,async(req,res)=>{ const emp=await getEmp(req.user.agenciaId); try{ const r=await fetch(`https://graph.facebook.com/v20.0/${req.params.mediaId}?access_token=${emp.token}`); const j=await r.json(); const m=await fetch(j.url,{headers:{Authorization:`Bearer ${emp.token}`}}); res.set('Content-Type', m.headers.get('content-type')||'application/octet-stream'); res.send(Buffer.from(await m.arrayBuffer())); }catch(e){ res.status(500).json({error:e.message}); }});
app.get('/api/health',(req,res)=>res.json({ok:true, gerente:GERENTE_LINK})); app.get('/health',(req,res)=>res.json({ok:true}));
app.get('/',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
io.on('connection',s=>{ s.on('join_agencia',id=>s.join(`agencia_${id}`)); });
const PORT=process.env.PORT||3000; server.listen(PORT,()=>console.log(`🚀 KLIDO GERENTE ${GERENTE_LINK} clave ${GERENTE_CLAVE} - ${PORT}`));
